// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numTimes = integer.parseInt(args[0]);
		int bigger = 0;
		int smaller = 0;
		for (int i = 0; i < numTimes; i++) {
			double randValue = Math.random();
			for(randValue > 0.5){
				bigger++;
			} else {
				smaller++;
			};
			double ratio = (double)bigger / (double)smaller;
			System.out.println("> 0.5:  " + bigger + " times");
			System.out.println("<= 0.5:  " + smaller + " times");
			System.err.println("Ratio:  " + ratio);
		}
}
